version: '3'
services:
    test:
        image: robotframewoek_apitest:latest
        build: .
        volumes: 
            - ./results:/results
        ports: 
            - 8000:8000
        container_name: apirobot_docker
